# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: manual-pv
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: aws-ebs-sc
#   resources:
#     requests:
#       storage: 100Mi